version: "3.9"
services:
    mongodb:
        container_name: spice-ldh-mongodb
        build: 
            context: ./mongodb
            args:
                MONGO_INITDB_ROOT_USERNAME: admin
                MONGO_INITDB_ROOT_PASSWORD: MONGO1234567890
                MONGO_INITDB_DATABASE: admin
        volumes:
            - mongodata:/data/db
    blazegraph:
        container_name: spice-ldh-blazegraph
        image: nawer/blazegraph
        ports:
            - "8099:9999"
    api:
        container_name: spice-ldh-api
        build:
            context: ./api
            args:
                APIF_VERSION: v0.9.5
        ports:
            - "80:80"
    mysql:
        container_name: spice-ldh-mysql
        image: mysql/mysql-server:5.7
        environment:
            MYSQL_DATABASE: spice_datahub
            #MYSQL_USER: admin
            #MYSQL_PASSWORD: NMg17ruPknQSC2rF
            MYSQL_ROOT_PASSWORD: NMg17ruPknQSC2rF
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    portal:
        container_name: spice-ldh-portal
        build:
            context: ./portal
            args:
                PORTAL_VERSION: v0.2.1
        ports:
            - "8091:80"
    contentscanner:
        container_name: spice-ldh-scanner
        build: 
            context: ./contentscanner
            args:
                SCANNER_VERSION: v0.5.1
volumes:
  mongodata:
